name: presentation
description: Presentation layer
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=2.2.0"
 

dependencies:
  flutter:
    sdk: flutter

  data:
    path: ../data
  # domain:
  #   path: ../domain


  flutter_svg: ^0.22.0
  rxdart: ^0.27.5
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.1.0
  faker: ^2.0.0
  google_fonts: ^2.1.0
  jiffy: ^4.1.0
  logger: ^1.1.0
  flutter_neumorphic: ^3.1.0
  flutter_hooks: ^0.18.5+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # mockito: ^5.1.0
  # build_runner: ^2.1.8

# flutter:
#   generate: true

#   assets:
#     - ../../assets/svg/
