name: domain
description: Domain layer
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.2.0
  uuid: ^3.0.6
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.1
  firebase_auth: ^3.5.0
  equatable:
  firebase_storage: ^10.3.4
  rxdart: ^0.27.5
  google_sign_in: ^5.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
 